---
title: "Reglas de Asociación Radiografia"
author: "Elizaveta, Javier y Adrián"
date: "24/5/2020"
output:
  prettydoc::html_pretty:
    theme: caiman
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Estos datos contienen radiografías de tórax de casos de COVID-19. Créditos a Joseph Paul Cohen por abrir este conjunto de datos en Github.

```{r,warning=FALSE ,results=FALSE,message=FALSE}
library(readr)
library(dplyr)
library(arules)
library(arulesViz)

```

```{r,warning=FALSE}
metadata <- read.csv("https://raw.githubusercontent.com/ieee8023/covid-chestxray-dataset/master/metadata.csv")
covid<- metadata %>%
  select(intubated,intubation_present,went_icu,in_icu,needed_supplemental_O2,extubated,pO2_saturation,leukocyte_count,neutrophil_count,lymphocyte_count)

```

## Discretizo los valores : 

```{r}
attach(covid)
covid$pO2_saturation<-discretize(covid$pO2_saturation,breaks=5,labels=c("muy poco","poco","normal","alta","muy alta"))


covid$leukocyte_count<-discretize(covid$leukocyte_count,breaks=3,labels=c("poco","normal","muy alta"))

covid$neutrophil_count<-discretize(covid$neutrophil_count,breaks=3,labels=c("poco","normal","muy alta"))

covid$lymphocyte_count<-discretize(covid$lymphocyte_count,breaks=3,labels=c("poco","normal","muy alta"))

```


## Se aplica el algoritmo Apriori:

```{r,results=FALSE}
reglas <- apriori(covid,parameter = list(support=0.005,conf=1))

inspect(reglas)

```

## A continuación se van a ver algunas visualizaciones de las reglas sacadas:



```{r,warning=FALSE}
plot(reglas)

plot(reglas, method="matrix", engine="htmlwidget")

```


```{r,warning=FALSE}

subrules2 <- sample(reglas, 5)


plot(subrules2, method="graph", engine="graphviz")


plot(subrules2, method="graph", engine="htmlwidget")
plot(subrules2, method="graph", engine="htmlwidget", 
     igraphLayout = "layout_in_circle")


```




